### ISSUE TITLE
Develop tests for age_calc

### ISSUE THREAD

**Issue by jsonbecker** [jknowles/eeptools#16]
I need to develop tests for `age_calc` to ensure that future changes do not result in regressions and the algorithm is accurate.

This will need to test all options

- [x] `precise=TRUE, units='days'`
- [x] `precise=FALSE, units='days'`
- [x] `precise=TRUE, units='months'`
- [x] `precise=FALSE, units='months'`
- [x] `precise=TRUE, units='years'`
- [x] `precise=FALSE, units='years'`

There will need to be test data for:
- [x] an atomic `dob` and vector `enddate`
- [x] an atomic `enddate` and vector `dob`
- [x] vector `dob` and vector `enddate`
- [ ] both `dob` and/or `enddate` in leap years
- [x] `dob$yday > enddate$yday`
- [x] `dob$yday < enddate$yday`

**Comment by jknowles** [comment]
@jsonbecker I've almost actually completed all of these tests and I fixed one little bug reported about leap years. I know you're probably on to different things, but thought I'd let you know I'm bringing this up to speed for a new CRAN release soon.
