### ISSUE TITLE
Small bug with age_calc.R

### ISSUE THREAD

**Issue by larmarange** [jknowles/eeptools#25]
Dear jknowles,

I guess there is a very small bug with age_calc.R on line 24: https://github.com/jknowles/eeptools/blob/master/R/age_calc.R#L24

This condition can never been true as you test before if the month is Feb. Shouldn't you test first if it's Feb and leap year before to test if it's Feb?

`age_calc(as.Date('2004-01-15'),as.Date('2004-02-16'))`  is producing `1.035714`. `.035714` is equal to `1/28`, not to `1/29`.

Best regards

**Comment by jknowles** [comment]
Thanks @larmarange I have finally gotten around to patching this thanks to your detective work. I'm readying for a new `eeptools` release and the patch will be there.
