### ISSUE TITLE
Bug in age_calc (if -> vector)

### ISSUE THREAD

**Issue by MichaelChirico** [jknowles/eeptools#32]
The current implementation (0.9.1) of `age_calc` treats `enddate` and `dob` as scalars when testing for validity, while documentation suggests they can be vectors.

Current implementation:

```
if (enddate < dob) {
  stop("End date must be a date after date of birth")
}
```

Should be fixed to:

```
if (any(enddate < dob)) {
  stop("End date must be a date after date of birth")
}
```

**Comment by jknowles** [comment]
Fixed! Thanks.
