### ISSUE TITLE
Months calculation

### ISSUE THREAD

**Issue by ImanMez** [jknowles/eeptools#33]
Hello
first thanks for the code, 
but as I was running my calculations, I runned into a problem with the month units

**
Error in seq.int(r1$mon, 12 \* (to0$year - r1$year) + to0$mon, by) :
  'to' must be finite
**

and this one,

**
Error in seq.int(r1$mon, 12 \* (to0$year - r1$year) + to0$mon, by) :
  wrong sign in 'by' argument 
**

for the year calculation everything goes smoothly, i checked the format of my data and I couldn't spot on the problem.

Many thanks

**Comment by jsonbecker** [comment]
Sorry it took me a while to see this. can you give a small reproducible example, perhaps using https://github.com/tidyverse/reprex?
