### ISSUE TITLE
fix examples in theme_dpi_map

### ISSUE THREAD

**Issue by jangorecki** [jknowles/eeptools#34]
There is a call `library(reshape)` in examples - https://github.com/jknowles/eeptools/blob/master/man/theme_dpi_map.Rd#L30
As reshape is suggested dependency, it should not be required to run examples according to R-exts. This can be conditionally escaped with requireNamespace.
It is possible there are other cases of that issue in other examples, this one was to first that fails.

**Comment by jangorecki** [comment]
The same applies to `mapproj` suggested dep in the same examples
```
> ggplot(crimes, aes(map_id = state)) + geom_map(aes(fill = Murder), map = states_map) + 
+     expand_limits(x = states_map$long, y = states_map$lat)+ labs(title="USA Crime")
> # Draw map
> last_plot() + coord_map()
Error in loadNamespace(name) : there is no package called ‘mapproj’
Calls: <Anonymous> ... mapply -> <Anonymous> -> <Anonymous> -> f -> mproject
Execution halted
```

**Comment by jknowles** [comment]
Fixed. Thanks for the report.
